/**
 * primedl — cookies.js
 * Extracts cookies for a given tab URL and formats them for the relay payload.
 * Compatible with Chrome (all partitions) and Firefox (standard + first-party isolation).
 */

const isChrome = chrome.runtime.getURL("").startsWith("chrome-extension://");
const isFirefox = !isChrome;

/**
 * Get all cookies relevant to a URL.
 * Returns both a raw array and a Netscape-format string
 * (yt-dlp / curl compatible).
 */
export async function getCookiesForUrl(tabUrl) {
	if (!tabUrl || tabUrl.startsWith("about:") || tabUrl.startsWith("chrome:")) {
		return { cookies: [], netscape: "", cookieHeader: "" };
	}

	let url;
	try {
		url = new URL(tabUrl);
	} catch {
		return { cookies: [], netscape: "", cookieHeader: "" };
	}

	const domain = url.hostname;
	let cookies = [];

	// Primary query — by URL (most reliable, covers host + path)
	try {
		const byUrl = await chrome.cookies.getAll({ url: tabUrl });
		cookies = byUrl;
	} catch (e) {
		console.warn("[primedl/cookies] getAll by URL failed:", e);
	}

	// Firefox first-party isolation fallback
	// If FPI is enabled, the URL query above may return nothing
	if (isFirefox && cookies.length === 0) {
		try {
			const byDomain = await chrome.cookies.getAll({
				domain,
				firstPartyDomain: domain
			});
			cookies = byDomain;
		} catch {
			// FPI not enabled — ignore
		}
		// Also try null firstPartyDomain to catch everything
		if (cookies.length === 0) {
			try {
				const all = await chrome.cookies.getAll({
					url: tabUrl,
					firstPartyDomain: null
				});
				cookies = all;
			} catch {
				// ignore
			}
		}
	}

	// Deduplicate by name (keep last — most recently set wins)
	const seen = new Map();
	for (const c of cookies) {
		seen.set(c.name, c);
	}
	const deduped = [...seen.values()];

	return {
		cookies: deduped,
		netscape: toNetscape(deduped),
		cookieHeader: toCookieHeader(deduped)
	};
}

/**
 * Format cookies as a Netscape cookies.txt string.
 * This is what yt-dlp, curl --cookie-jar, and wget expect.
 *
 * Format per line:
 * domain  includeSubdomains  path  secure  expiry  name  value
 */
function toNetscape(cookies) {
	if (!cookies.length) return "";

	const lines = ["# Netscape HTTP Cookie File", "# Generated by primedl extension", ""];

	for (const c of cookies) {
		const domain = c.domain.startsWith(".") ? c.domain : `.${c.domain}`;
		const includeSubdomains = domain.startsWith(".") ? "TRUE" : "FALSE";
		const path = c.path || "/";
		const secure = c.secure ? "TRUE" : "FALSE";
		// Session cookies get a far-future expiry so tools don't reject them
		const expiry = c.expirationDate ? Math.floor(c.expirationDate).toString() : "0";
		const name = c.name;
		const value = c.value;

		lines.push([domain, includeSubdomains, path, secure, expiry, name, value].join("\t"));
	}

	return lines.join("\n");
}

/**
 * Format cookies as a Cookie header string.
 * Used for direct HTTP header injection in yt-dlp / curl commands.
 */
function toCookieHeader(cookies) {
	return cookies.map((c) => `${c.name}=${c.value}`).join("; ");
}
